export const path = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  RESETPASSWORD: "/reset-password",
  ADMIN: "/admin",
  ADMIN_USER: "/admin/user",
  ADMIN_ARTICLE: "/admin/article",
  ARTICLEDETAIL: "/article/:book_id",
  PAYMENT: "/payment",
  VOCABULARY: "/vocabulary",
  FLASHCARD: "/flashcard",
  BLOG: "/blog",
  ARTICLE: "/article",
};
