export const path = {
    HOME: "/",
    LOGIN: "/login",
    REGISTER: "/register",
    RESETPASSWORD: "/reset-password",
    ADMIN: "/admin",
    ADMIN_USER: "/admin/user",
    ADMIN_ARTICLE: "/admin/article",
    ADMIN_QUIZ: "/admin/quiz",
    ARTICLE_DETAIL: "/article/:book_id",
    VOCABULARY: "/vocabulary",
    FLASHCARD: "/flashcard",
    USER_FLASHCARD: "/flashcards",
    USER_ARTICLE: "/articles",
    QUESTION: "/questions",
    QUIZ: "/quiz",
    QUIZ_ATTEMPT: "/quiz-attempt",
    LIBRARY: "/library",
};